export const ON_LOAD = 'ON_LOAD';
export const ON_LOAD_ERROR = 'ON_LOAD_ERROR';

export const SHOW_MODAL = 'SHOW_MODAL';
export const CLOSE_MODAL = 'CLOSE_MODAL';

export const SIGN_OUT = 'SIGN_OUT';

export const SIGN_IN_REQUEST = 'SIGN_IN_REQUEST';
export const SIGN_IN_SUCCESS = 'SIGN_IN_SUCCESS';
export const SIGN_IN_ERROR = 'SIGN_IN_ERROR';

export const SIGN_UP_REQUEST = 'SIGN_UP_REQUEST';
export const SIGN_UP_SUCCESS = 'SIGN_UP_SUCCESS';
export const SIGN_UP_ERROR = 'SIGN_UP_ERROR';

export const CONFIRM_SIGN_UP_REQUEST = 'CONFIRM_SIGN_UP_REQUEST';
export const CONFIRM_SIGN_UP_ERROR = 'CONFIRM_SIGN_UP_ERROR';

export const GET_CASES_REQUEST = 'GET_CASES_REQUEST';
export const GET_CASES_SUCCESS = 'GET_CASES_SUCCESS';
export const GET_CASES_ERROR = 'GET_CASES_ERROR';

export const GET_ONE_CASE_REQUEST = 'GET_ONE_CASE_REQUEST';
export const GET_ONE_CASE_SUCCESS = 'GET_ONE_CASE_SUCCESS';
export const GET_ONE_CASE_ERROR = 'GET_ONE_CASE_ERROR';

export const GET_PROFILE_REQUEST = 'GET_PROFILE_REQUEST';
export const GET_PROFILE_SUCCESS = 'GET_PROFILE_SUCCESS';
export const GET_PROFILE_ERROR = 'GET_PROFILE_ERROR';

export const GET_USER_REQUEST = 'GET_USER_REQUEST';
export const GET_USER_SUCCESS = 'GET_USER_SUCCESS';
export const GET_USER_ERROR = 'GET_USER_ERROR';

export const CHANGE_TAB_REQUEST = 'CHANGE_TAB_REQUEST';
export const CHANGE_TAB_SUCCESS = 'CHANGE_TAB_SUCCESS';
export const CHANGE_TAB_ERROR = 'CHANGE_TAB_ERROR';

export const SWITCH_TAB = 'SWITCH_TAB';

export const UNBLOCK_RIGHT_TAB_TOP = 'UNBLOCK_RIGHT_TAB_TOP';
export const SWITCH_RIGHT_TAB_TOP = 'SWITCH_RIGHT_TAB_TOP';

export const UNBLOCK_RIGHT_TAB_BOTTOM = 'UNBLOCK_RIGHT_TAB_BOTTOM';

export const SET_CHAT_REQUEST = 'SET_CHAT_REQUEST';
export const UPDATE_CHAT_REQUEST = 'UPDATE_CHAT_REQUEST';

export const SET_ANALYSER_REQUEST = 'SET_ANALYSER_REQUEST';
export const REMOVE_CURRENT_ANALYSER = 'REMOVE_CURRENT_ANALYSER';
export const REMOVE_HIGHLIGHT_ANALYSER = 'REMOVE_HIGHLIGHT_ANALYSER';